In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("e.csv")

In [3]:
data.head()

text label
0  Just got back from seeing @GaryDelaney in Burs...   joy
1  Oh dear an evening of absolute hilarity I don'...   joy
2  Been waiting all week for this game ❤️❤️❤️ #ch...   joy
3  @gardiner_love : Thank you so much, Gloria! Yo...   joy
4  I feel so blessed to work with the family that...   joy

In [4]:
data.shape

(3613, 2)

In [5]:
df=data.dropna()
df.shape

(3613, 2)

In [7]:
df.label.unique()

array(['joy', 'fear', 'anger', 'sadness'], dtype=object)

In [8]:
df.label.value_counts()

fear       1147
anger       857
joy         823
sadness     786
Name: label, dtype: int64

In [9]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [10]:
# remove whitespaces
df['text']=df['text'].str.strip()
# lowercase the text
df['text'] = df['text'].str.lower()
#remove punctuation
punc = string.punctuation
table = str.maketrans('','',punc)
df['text']=df['text'].apply(lambda x: x.translate(table))
# tokenizing each message
df['text']=df.apply(lambda x: x['text'].split(' '),axis=1)
# removing stopwords
df['text'] = df.apply(lambda x: [word for word in x['text'] if word not in stopwords.words('english')],axis=1)
# stemming
ps = PorterStemmer()
df['text']= df.apply(lambda x: [ps.stem(word) for word in x['text']],axis=1)
# remove single letter words
df['text'] = df.apply(lambda x: ' '.join([word for word in x['text'] if len(word)>1]),axis=1)


In [11]:
X = np.array(df["text"])
y = np.array(df["label"])

In [12]:
X[0]

'got back see garydelaney burslem amaz face still hurt laugh much hilari'

In [13]:
y[0:10]

array(['joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy',
       'joy'], dtype=object)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv_X = cv.fit_transform(X) # Fit the Data

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cv_X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression
cbc = LogisticRegression(verbose=0)
cbc.fit(X_train,y_train)

LogisticRegression()

In [17]:
predict = cbc.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score
print('Accuracy of LogisticRegression',accuracy_score(y_test,predict)*100)

Accuracy of LogisticRegression 86.16874135546335


In [19]:
from sklearn.metrics import confusion_matrix
print('Confusuion matrix of LogisticRegression\n',confusion_matrix(y_test,predict))

Confusuion matrix of LogisticRegression
 [[133   9   2  10]
 [  6 199   1  17]
 [  3   9 170   3]
 [ 11  22   7 121]]


In [20]:
from sklearn.metrics import classification_report
print('Classification report of LogisticRegression\n\n',classification_report(y_test,predict))

Classification report of LogisticRegression

               precision    recall  f1-score   support

       anger       0.87      0.86      0.87       154
        fear       0.83      0.89      0.86       223
         joy       0.94      0.92      0.93       185
     sadness       0.80      0.75      0.78       161

    accuracy                           0.86       723
   macro avg       0.86      0.86      0.86       723
weighted avg       0.86      0.86      0.86       723

